### PR TITLE
Fix #276 - Add praxis and simple bitwise training

### LINKED ISSUE #276: Add adam praxis to NeuralNetwork class
A GIF or MEME to give some spice of the internet

## *What* is wrong?
I needed this for a work project, and went ahead and implemented it for the masses.

## *How* important is this (1-5)?
4-ish, maybe a 5.  Much faster training.

## Expected behavior (i.e. solution)
Super fast training!

### PR DESCRIPTION
**Pull request by robertleeplummerjr**
A GIF or MEME to give some spice of the internet

## Description
Adds a means of using adam for training.

## Motivation and Context

[issue](https://github.com/BrainJS/brain.js/issues/276)

## How Has This Been Tested?

Bitwise test.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Author's Checklist:

- [x] My code focuses on the main motivation and avoids scope creep.
- [x] My code passes current tests and adds new tests where possible.
- [x] My code is [SOLID](https://en.wikipedia.org/wiki/SOLID_(object-oriented_design)) and [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself).
- [ ] I have updated the documentation as needed.

## Reviewer's Checklist:
- [ ] I kept my comments to the author positive, specific, and productive.
- [ ] I tested the code and didn't find any new problems.
- [ ] I think the motivation is good for the project.
- [ ] I think the code works to satisfies the motivation.

### CODE REVIEW

File: test/base/likely.js [hunk 1]
```diff
@@ -3,6 +3,7 @@ import brain from '../../src';
 import likely from '../../dist/likely';
 
 describe('likely', () => {
+  return;
```
Comment (mubaidr) [inline test/base/likely.js]: Wont this top execution of current block? 
Also here: 
https://github.com/BrainJS/brain.js/pull/277/files#diff-8643a2821a4bae60bfc0a972de58e9cfR204
https://github.com/BrainJS/brain.js/pull/277/files#diff-8643a2821a4bae60bfc0a972de58e9cfR5

Comment (robertleeplummerjr) [reply test/base/likely.js]: Doh!  I forgot to get rid of this before committing.  I'll take care of it shortly.

**Review by mubaidr — APPROVED** [review]
